(define (same-parity x . y)
  (define (same-parity_ l)
    (if (null? l)
      (list)
      (if (= (mod x 2) (mod (car l) 2))
        (cons (car l) (same-parity_ (cdr l)))
        (same-parity_ (cdr l)))))
  (cons x (same-parity_ y)))

(display (same-parity 1 2 3 4 5))
